server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_order_db
    username: postgres
    password: 5656

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Resilience4j (optional, tweak as you like)
resilience4j:
  circuitbreaker:
    instances:
      productClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      paymentClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productClient:
        maxAttempts: 3
        waitDuration: 200ms
      paymentClient:
        maxAttempts: 3
        waitDuration: 200ms

