server:
  port: 8080

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_order_db
    username: postgres
    password: 5656

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# example custom prop from config server
product:
  discount:
    rate: 0.05
