server:
  port: 8080

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_order_db
    username: postgres
    password: 5656
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

